
FROM python:3.11-slim

RUN apt-get update
RUN apt-get install -y libpq-dev gcc

ADD sim-ops-lib/requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir /app
COPY sim-ops-lib/ /app
WORKDIR /app

RUN python -c "import skyfield.api; skyfield.api.load('de421.bsp')"

ENTRYPOINT [ "python", "so-master.py" ]
